name: savior
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  provider: ^6.0.0
  conditional_builder_null_safety: ^0.0.6
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  dio: ^4.0.0
  hexcolor: ^2.0.3
  shared_preferences: ^2.0.5
  lottie: ^1.0.1
  modal_bottom_sheet: ^2.0.0
  flutter_native_timezone: ^2.0.0
  flutter_local_notifications: ^9.3.3
  rxdart: ^0.27.3
  image_picker: ^0.8.4+10
  cached_network_image: ^3.2.0
  flutter_svg: ^1.0.3
  # social_media_recorder: ^0.1.61
  # record: ^3.0.0
  flutter_mentions: ^2.0.1
  flutter_reaction_button: ^2.0.0+2
  path_provider: ^2.0.9
  logging: ^1.0.1
  hooks_riverpod: ^2.0.0-dev.0
  font_awesome_flutter: ^10.1.0
  flutter_datetime_picker: ^1.5.1
  country_picker: ^2.0.15
  timeago: ^3.2.2
  percent_indicator: ^4.2.1
  social_share: ^2.2.1
  get: ^4.6.5
  shimmer: ^2.0.0
  flutter_speed_dial: ^6.0.0
  flutter_launcher_icons: ^0.10.0
  
  #firebase
  firebase_auth: ^3.3.13
  firebase_core: ^1.14.0
  cloud_firestore: ^3.1.11
  firebase_messaging: ^11.2.12
  firebase_storage: ^10.2.11

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_color: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/
    - assets/audios/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
